<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_srch</name>
   <tag></tag>
   <elementGuidId>b50d0607-f492-430f-b70a-ecc06c2dea37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//input[@aria-controls='tblActivityCreation']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
